### ISSUE TITLE
Error handling FastAPI RequestValidationError when errors contains non serializable objects

### ISSUE THREAD

**Issue by g0di** [g0di/fastapi-problem-details#5]
The error handler binded to  fastapi `RequestValidatorError` is not working when the error contains objects which are not serializable.

```bash
ERROR    fastapi_problem_details.error_handlers:error_handlers.py:65 Unhandled exception
Traceback (most recent call last):
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 315, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, Either "email" or "phone" are required', 'input': {'email': None, 'phone': None, 'signUpDate': '2024-10-01', 'role': 'admin'}, 'ctx': {'error': ValueError('Either "email" or "phone" are required')}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 75, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/fastapi_problem_details/error_handlers.py", line 27, in handle_validation_error
    return ProblemResponse(
           ^^^^^^^^^^^^^^^^
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/fastapi_problem_details/models.py", line 132, in __init__
    problem.model_dump(mode="json"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gody/Development/Healthblocks/user-api/.venv/lib/python3.11/site-packages/pydantic/main.py", line 364, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'ValueError'>
```

**Comment by g0di** [comment]
Resolved by commit b9769fbbfb6279e62776f93c20c27e7bf3d7062a
